location = /dopamine { return 301 https://frkn.app/$is_args$args; }
location = /dopamine/ { return 301 https://frkn.app/$is_args$args; }
location = /dopamine/index.html { return 301 https://frkn.app/$is_args$args; }
location = /dopamine/en { return 301 https://frkn.app/en/$is_args$args; }
location = /dopamine/en/ { return 301 https://frkn.app/en/$is_args$args; }
location = /dopamine/en/index.html { return 301 https://frkn.app/en/$is_args$args; }
location = /en/dopamine { return 301 https://frkn.app/en/$is_args$args; }
location = /en/dopamine/ { return 301 https://frkn.app/en/$is_args$args; }
location = /en/dopamine/index.html { return 301 https://frkn.app/en/$is_args$args; }

location = /selfhosted { return 301 https://frkn.app/selfhosted/$is_args$args; }
location = /selfhosted/ { return 301 https://frkn.app/selfhosted/$is_args$args; }
location = /selfhosted/index.html { return 301 https://frkn.app/selfhosted/$is_args$args; }
location = /en/selfhosted { return 301 https://frkn.app/en/selfhosted/$is_args$args; }
location = /en/selfhosted/ { return 301 https://frkn.app/en/selfhosted/$is_args$args; }
location = /en/selfhosted/index.html { return 301 https://frkn.app/en/selfhosted/$is_args$args; }

location = /setup/dopamine { return 301 https://frkn.app/setup/$is_args$args; }
location = /setup/dopamine/ { return 301 https://frkn.app/setup/$is_args$args; }
location = /setup/dopamine/index.html { return 301 https://frkn.app/setup/$is_args$args; }
location = /en/setup/dopamine { return 301 https://frkn.app/en/setup/$is_args$args; }
location = /en/setup/dopamine/ { return 301 https://frkn.app/en/setup/$is_args$args; }
location = /en/setup/dopamine/index.html { return 301 https://frkn.app/en/setup/$is_args$args; }
location = /fa/setup/dopamine { return 301 https://frkn.app/en/setup/$is_args$args; }
location = /fa/setup/dopamine/ { return 301 https://frkn.app/en/setup/$is_args$args; }
location = /fa/setup/dopamine/index.html { return 301 https://frkn.app/en/setup/$is_args$args; }
